import type { Metadata } from "next";
// Roboto ফন্ট ইমপোর্ট করা হলো
import { Roboto } from "next/font/google"; 
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Roboto ফন্ট কনফিগারেশন: weight এবং subsets নির্দিষ্ট করা হয়েছে
const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'], // প্রয়োজনীয় weight গুলো এখানে দিন
  subsets: ["latin"],
  variable: "--font-roboto", // CSS ভ্যারিয়েবল নাম
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* বডিতে Roboto ফন্ট ভ্যারিয়েবল ব্যবহার করা হয়েছে */}
      <body
        className={`${roboto.variable} font-sans antialiased`} 
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}